### ISSUE TITLE
[S2-12] "Facebook/Google registration" API

### ISSUE THREAD

**Issue by nhoknguyen00** [LMN-Team/itedu-user-api#20]
Cho phép người dùng thực hiện đăng ký với facebook/google

**Comment by TranTLy** [comment]
@nhoknguyen00 
Lỗi CORS khi login/ signup with fb/gg
Nhờ ông xem lại giúp nha.
Thanks.

![image](https://user-images.githubusercontent.com/25228809/69641256-74dafe00-1092-11ea-9f20-71b2b7880707.png)

**Comment by hminh21** [comment]
@nhoknguyen00 include thêm `https://www.facebook.com` với `https://www.google.com` vào cors nha Nguyên

**Comment by TranTLy** [comment]
@nhoknguyen00 
Trong file userController.js, ông chỉnh **httpOnly** từ true thành false thì t mới đọc dc access_token nha Nguyên. Thanks nha
![image](https://user-images.githubusercontent.com/25228809/69745442-c8257d00-1174-11ea-92e6-bcdb9c33f757.png)
