### ISSUE TITLE
[S2-09] Forget Password

### ISSUE THREAD

**Issue by duyminh256** [LMN-Team/itedu-user-api#23]

**Comment by hminh21** [comment]
Gắn ticket với label vô nha

**Comment by TranTLy** [comment]
@duyminh256 
Lỗi khi thay đổi mật khẩu
<p align="center">
Hình 1: backend
</p>

![image](https://user-images.githubusercontent.com/25228809/69611453-5e1bb380-1060-11ea-9a87-4d3784d7773c.png)


<p align="center">
Hình 2: frontend báo lỗi 500
</p>

![image](https://user-images.githubusercontent.com/25228809/69610990-75a66c80-105f-11ea-8e78-b4760e6ecc20.png)

**Comment by duyminh256** [comment]
Đã fix rồi nha Lý

**Comment by duyminh256** [comment]
Đã fix bug @TranTLy . Đã change route cho đồng bộ @nhoknguyen00
