### ISSUE TITLE
[S2-13] API /user/me

### ISSUE THREAD

**Issue by TranTLy** [LMN-Team/itedu-user-api#26]
get basic user's info

**Comment by nhoknguyen00** [comment]
![image](https://user-images.githubusercontent.com/49438442/69911346-c269b900-144c-11ea-88c0-fe7fc7c4c6c7.png)
![image](https://user-images.githubusercontent.com/49438442/69911347-c7c70380-144c-11ea-8a25-deea4cd4f174.png)
tui login bằng facebook nó bị bug hay sao ấy, nó báo user/me là 401, đăng nhập zo thì frontend báo là Hello, Lưu Tuấn Nguyên là tên account đăng ký basic, mà trong khi tên facebook tui là Mike D. Tuấn Nguyên
Flow: đăng ký basic trước => kích hoạt => đăng nhập với account basic => đăng nhập bằng google (trùng email với đăng ký basic) => thành công => đăng nhập bằng facebook => lỗi như trên

**Comment by TranTLy** [comment]
@nhoknguyen00 T đã check lại source code, hiện tại t đang lấy thông tin user dựa vào id của user. Có thể do một email chỉ tạo được 1 tài khoản, displayName đó là thông tin của user tại lần đầu tiên đăng ký (nếu dky bằng fb thì sẽ là tên trên fb, tương tự cho gg hoặc tên người dùng tự nhập lúc đăng ký bằng email+pass). Tên này sẽ không tự động cập nhật khi người dùng đăng nhập.
