### ISSUE TITLE
[S3-25] Code refactor

### ISSUE THREAD

**Issue by nhoknguyen00** [LMN-Team/itedu-user-api#55]

**Comment by hminh21** [comment]
Theo ý t, trừ controller với service ra, tất cả dùng lại như cũ. Lí do:
1. Mình sẽ kiểm soát được những thứ mình cần dùng
2. Tránh phân 3, 4 cấp quá nhiều làm cho code rối hơn
ex: `utils.crypt.createActivateEmailToken`, `utils.debug.error(NAMESPACE, 'Unable to connect to the database:', err)`, `utils.enums.MESSAGE.OK`
3. Đừng lạm dụng việc import hết tất module kể cả những thứ mình k dùng tới, file nào cũng làm vậy sẽ tăng size của bundler lên 
https://madewithlove.be/optimizing-javascript-packages-for-tree-shaking/
https://stackoverflow.com/questions/57161869/es6-modules-3-ways-of-importing-files
4. Thực tế thì có những module mình nhìn tên thôi cũng biết nó dùng để làm gì và nằm ở đâu luôn rồi (Nếu biết cách đặt tên).
Ví dụ như:
- Biến constant luôn nằm trong config
- debug, enums, crypt => function tiện ích => utils
- mail => 3rd service => fetch
- Auth dùng trong route `router.get('/me', auth(), userController.getBasicUserInfo)` => middleware

**Comment by nhoknguyen00** [comment]
t có tạo pull request mà, sao ko cmt trong pull request :)

**Comment by hminh21** [comment]
có review gì trong code đâu mà phải comment trong đó

**Comment by hminh21** [comment]
Resolved
