### ISSUE TITLE
[S5-05] Watch video course

### ISSUE THREAD

**Issue by TranTLy** [LMN-Team/itedu-user-api#69]

**Comment by TranTLy** [comment]
#69 
Example for response:
{
    "message": "Success",
    "payload": {
        "024a0f4c-1f43-4b3c-8d31-6d385cd930da": {
            "id": "024a0f4c-1f43-4b3c-8d31-6d385cd930da",
            "courseId": "9a086d90-ae9f-48fa-9013-20501d320704",
            "numberOrder": 1,
            "name": "Giới thiệu",
            "createdAt": "2020-01-29T06:08:28.025Z",
            "updatedAt": "2020-01-29T06:08:28.025Z",
            "lesson": [
                {
                    "id": "33ff5508-9413-442c-af1a-9d32613c77c7",
                    "courseId": "9a086d90-ae9f-48fa-9013-20501d320704",
                    "sectionId": "024a0f4c-1f43-4b3c-8d31-6d385cd930da",
                    "numberOrder": 1,
                    "name": "Đây là tên của bài 1",
                    "content": "Đây là nội dung",
                    "videoName": "video.mp4",
                    "hours": 0,
                    "isDeleted": false,
                    "createdAt": "2020-01-29T06:08:28.035Z",
                    "updatedAt": "2020-01-29T06:08:28.035Z"
                }
            ]
        },
        "isNotFirst": true,
        "6ac7f7fd-33ab-4942-8916-034310e0530f": {
            "id": "6ac7f7fd-33ab-4942-8916-034310e0530f",
            "courseId": "9a086d90-ae9f-48fa-9013-20501d320704",
            "numberOrder": 2,
            "name": "Nhập môn",
            "createdAt": "2020-01-29T06:08:28.025Z",
            "updatedAt": "2020-01-29T06:08:28.025Z",
            "lesson": [
                {
                    "id": "bc4fe50b-c0a1-4c3d-823d-352a24b1c95c",
                    "courseId": "9a086d90-ae9f-48fa-9013-20501d320704",
                    "sectionId": "6ac7f7fd-33ab-4942-8916-034310e0530f",
                    "numberOrder": 2,
                    "name": "Đây là tên của bài 2",
                    "content": "Đây là nội dung",
                    "videoName": "video.mp4",
                    "hours": 0,
                    "isDeleted": false,
                    "createdAt": "2020-01-29T06:08:28.035Z",
                    "updatedAt": "2020-01-29T06:08:28.035Z"
                }
            ]
        }
    }
}

**Comment by TranTLy** [comment]
#69
Example for response:
![image](https://user-images.githubusercontent.com/25228809/73376628-5393c980-42f0-11ea-8e4e-020f68197f7e.png)

![image](https://user-images.githubusercontent.com/25228809/73376661-61494f00-42f0-11ea-9ae4-e0fa974aa42b.png)

![image](https://user-images.githubusercontent.com/25228809/73376817-9fdf0980-42f0-11ea-8472-7a3f641bdc57.png)

**Comment by hminh21** [comment]
Resolved
