### ISSUE TITLE
[S2-02]"User registration with activated email" feature in user api

### ISSUE THREAD

**Issue by nhoknguyen00** [LMN-Team/itedu-user-api#7]
User signs up into application.
A user cannot sign in yet into application until their email is verified.
A user receives an email with a verification link that contains a token.
User clicks on verification link to get redirected to the application where the token is used to verify them.

**Comment by hminh21** [comment]
@nhoknguyen00 please attach the ID ticket to your issue's name

**Comment by hminh21** [comment]
@nhoknguyen00 this label is feature, not enhancement :D

**Comment by nhoknguyen00** [comment]
User đăng kí tài khoản -> frontend gửi thông tin lên user api -> api thêm user trên database nhưng isActivated = false và gửi email chứa link activate có active_jwt_token tới user email

User cần click link trong email (gmail thì có hiện nút click đẹp đẹp, outlook thì ko :(() -> link dẫn đến frontend -> frontend lấy jwt trong link gửi đến route "/user/activate-email" để kích hoạt tài khoản

**Comment by TranTLy** [comment]
![itedu-2](https://user-images.githubusercontent.com/25228809/69361513-3a9ee480-0cbf-11ea-951b-1a247124136d.PNG)
![itedu-1](https://user-images.githubusercontent.com/25228809/69361514-3a9ee480-0cbf-11ea-8cd9-4a410899486f.PNG)

Cần config lại cors để front-end có thể gọi api của backend

**Comment by hminh21** [comment]
@TranTLy sorry lỗi tui đặt cors là ip mà trong config lại để url là localhost, sửa luôn dùm tui nha
![image](https://user-images.githubusercontent.com/46931196/69362069-62db1300-0cc0-11ea-95d3-b644f86823a2.png)
